<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f399872e-a573-40ea-ad4d-6b0e539ce5e7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" />
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.AspNetCore" />

    <PackageReference Include="Mapster" />
    <PackageReference Include="Mapster.DependencyInjection" />

    <PackageReference Include="EFCore.NamingConventions" />

    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />


    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />

    <PackageReference Include="Serilog.AspNetCore" />

    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RealWorldApi.Infrastructure\RealWorldApi.Infrastructure.csproj" />
    <ProjectReference Include="..\RealWorldApi.ServiceDefaults\RealWorldApi.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
